### ISSUE TITLE
Any plan to upgrade to latest lz4 1.9.2?

### ISSUE THREAD

**Issue by hanabi1224** [cruise-automation/wasm-lz4#4]

**Comment by janpaul123** [comment]
Currently no plans from our end, but we'd be happy to take a PR if you want to make one. It might be cool to try the new `LZ4_FAST_DEC_LOOP` flag, I wonder how much difference that would make!

**Comment by hanabi1224** [comment]
Hmm, I have some rust/dart code from other projects that binds to lz4 1.9.2, the rust part could compile to wasm with modifications but it does not seem to be compatible with this project : )
